# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonbelt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hired_date',
            new_name='date_hired',
        ),
    ]
